# Generated by Django 3.0 on 2020-11-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/static/pics/None/no-img.png', upload_to='static/pics/'),
        ),
    ]
