# Generated by Django 3.0 on 2020-11-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201130_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/pics/None/no-img.png', upload_to='static/pics/'),
        ),
    ]
